create  table production(product_id int primary key,product_name varchar(20),brand_id int,category_id int, model_year int, price_list int)
insert into production values(1,'tv',123,234,2019,78945)
insert into production values(2,'mobile',124,135,2020,76989)
insert into production values(3,'charger',125,136,2021,54677)
insert into production values(4,'laptop')
insert into production values(5,'LED light')
insert into production values(6,'fan')
insert into production values(7,'cooler')
insert into production values(8,'frige')
insert into production values(9,'usb')
insert into production values(10,'tube light')
insert into production values(11,'table fan'
insert into production values(12,'')
